### PR TITLE
Update for kubernetes 1.22

### PR DESCRIPTION
**Pull request by cmurphy**
Update ValidatingWebhookConfiguration and ClusterRole resources to use
apiVersion v1 for compatibility with kubernetes 1.22.

https://github.com/rancher/rancher/issues/33513

### CODE REVIEW

**Review by rawmind0 — APPROVED** [review]
LGTM

**Review by cbron — APPROVED** [review]
Code changes lgtm, but we'll need to bump the major version of the chart to go into 2.6, to make sure this only ends up in 2.6, as 1.15 doesn't support v1beta1.

**Comment by cmurphy** [comment]
~~I added `catalog.cattle.io/rancher-version: '>= 2.6.0-alpha'` to make sure this only deploys on 2.6.~~ switched this to `kubeVersion`

**Review by cbron — CHANGES_REQUESTED** [review]
Since 1.0.0 was tagged this needs to wait for 2.6.1 and another version bump

**Comment by cmurphy** [comment]
2.6 was branched in rancher so bumping this

**Comment by cbron** [comment]
There was a fix for this in 1.21, might not need to update. Will circle back around after 2.6.0

**Pull request closed without merging**
